FROM nginx:1.24

# Copia la pagina web donde debería
RUN rm -rf /usr/share/nginx/html/index.html
COPY compiledPage/  /usr/share/nginx/html/
# Actualiza
RUN apt update

# Reemplaza el fichero de configuracion de nginx por el nuestro
COPY nginxConf/nginx_default.conf /etc/nginx/conf.d/default.conf
COPY nginxConf/nginx_global.conf /etc/nginx/nginx.conf

# Comprueba que los ficheros de configuracion de nginx estan bien y lo reinicia
RUN nginx -t

# Expongo el puerto 80
EXPOSE 80
