ktor:
    application:
        modules:
            - com.astrais.ApplicationKt.module
    deployment:
        port: ${?KTOR_PORT:-5684}

jwt:
    issuer: ${?JWT_ISSUER:-"ASTRAIS.ISSUER"}
    audience: ${?JWT_AUDIENCE:-"ASTRAIS.AUDIENCE"}
    accessSecret: ${?JWT_SECRET_ACCESS:-"ASTRAIS.FIRMA.A.CAMBIAR."}
    refreshSecret: ${?JWT_SECRET_REFRESH:-"ASTRAIS.FIRMA.A.CAMBIAR."}

db:
    user: ${?DB_USER:-"root"}
    password: ${?DB_PASSWORD:-"root"}
    dbname: ${?DB_NAME:-"db"}

oauth:
    google:
        clientId: ${?GOOGLE_CLIENT_ID:-"GOOGLE_CLIENT_ID"}
        clientSecret: ${?GOOGLE_CLIENT_SECRET:-"GOOGLE_CLIENT_SECRET"}