ktor:
    application:
        modules:
            - com.astrais.ApplicationKt.module
    deployment:
        port: ${KTOR_PORT}

jwt:
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    accessSecret: ${JWT_SECRET_ACCESS}
    refreshSecret: ${JWT_SECRET_REFRESH}

db:
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    dbname: ${DB_NAME}
